== Getting Started

=== Project Overview

* Architecture:
https://en.wikipedia.org/wiki/Single-page_application[Single Page Application (SPA)]
* Languages
 ** Front end is https://clojurescript.org/[ClojureScript] with (https://github.com/day8/re-frame[re-frame])
* Dependencies
 ** UI framework: https://github.com/day8/re-frame[re-frame]
(https://github.com/day8/re-frame/blob/master/docs/README.md[docs],
https://github.com/day8/re-frame/blob/master/docs/FAQs/README.md[FAQs]) \->
https://github.com/reagent-project/reagent[Reagent] \->
https://github.com/facebook/react[React]
* Build tools
 ** CLJS compilation, dependency management, REPL, & hot reload: https://github.com/thheller/shadow-cljs[`shadow-cljs`]
* Development tools
 ** Debugging: https://github.com/binaryage/cljs-devtools[CLJS DevTools],
https://github.com/day8/re-frame-10x[`re-frame-10x`]
 ** Emacs integration: https://github.com/clojure-emacs/cider[CIDER]

==== Directory structure

* `/`: project config files
* `dev/`: source files compiled only with the <<running-the-app,dev>> profile
 ** `user.cljs`: symbols for use during development in the
<<connecting-to-the-browser-repl-from-a-terminal,ClojureScript REPL>>
* `resources/public/`: SPA root directory;
<<running-the-app,dev>> / <<production,prod>> profile depends on the most recent build
 ** `index.html`: SPA home page
  *** Dynamic SPA content rendered in the following `div`:
+
[source,html]
----
  <div id="app"></div>
----

  *** Customizable; add headers, footers, links to other scripts and styles, etc.
 ** Generated directories and files
  *** Created on build with either the <<running-the-app,dev>> or <<production,prod>> profile
  *** `js/compiled/`: compiled CLJS (`shadow-cljs`)
   **** Not tracked in source control; see `.gitignore`
* `src/web_app/`: SPA source files (ClojureScript,
https://github.com/Day8/re-frame[re-frame])
 ** `core.cljs`: contains the SPA entry point, `init`

=== Editor/IDE

Use your preferred editor or IDE that supports Clojure/ClojureScript development. See
https://clojure.org/community/resources#_clojure_tools[Clojure tools] for some popular options.

=== Environment Setup

. Install https://openjdk.java.net/install/[JDK 8 or later] (Java Development Kit)
. Install https://nodejs.org/[Node.js] (JavaScript runtime environment) which should include
https://docs.npmjs.com/cli/npm[NPM] or if your Node.js installation does not include NPM also install it.
. Clone the project repo and open a terminal in the `web-app` project root directory

=== Browser Setup

Browser caching should be disabled when developer tools are open to prevent interference with
https://github.com/thheller/shadow-cljs[`shadow-cljs`] hot reloading.

Custom formatters must be enabled in the browser before
https://github.com/binaryage/cljs-devtools[CLJS DevTools] can display ClojureScript data in the
console in a more readable way.

==== Chrome/Chromium

. Open https://developers.google.com/web/tools/chrome-devtools/[DevTools] (Linux/Windows: `F12`
or `Ctrl-Shift-I`; macOS: `⌘-Option-I`)
. Open DevTools Settings (Linux/Windows: `?` or `F1`; macOS: `?` or `Fn+F1`)
. Select `Preferences` in the navigation menu on the left, if it is not already selected
. Under the `Network` heading, enable the `Disable cache (while DevTools is open)` option
. Under the `Console` heading, enable the `Enable custom formatters` option

==== Firefox

. Open https://developer.mozilla.org/en-US/docs/Tools[Developer Tools] (Linux/Windows: `F12` or
`Ctrl-Shift-I`; macOS: `⌘-Option-I`)
. Open https://developer.mozilla.org/en-US/docs/Tools/Settings[Developer Tools Settings]
(Linux/macOS/Windows: `F1`)
. Under the `Advanced settings` heading, enable the `Disable HTTP Cache (when toolbox is open)`
option

Unfortunately, Firefox does not yet support custom formatters in their devtools. For updates, follow
the enhancement request in their bug tracker:
https://bugzilla.mozilla.org/show_bug.cgi?id=1262914[1262914 - Add support for Custom Formatters in devtools].

== Development

=== Running the App

Start a temporary local web server, build the app with the `dev` profile, and serve the app,
browser test runner and karma test runner with hot reload:

[source,sh]
----
npm install
npx shadow-cljs watch app
----

Please be patient; it may take over 20 seconds to see any output, and over 40 seconds to complete.

When `[:app] Build completed` appears in the output, browse to
http://localhost:8280/.

https://github.com/thheller/shadow-cljs[`shadow-cljs`] will automatically push ClojureScript code
changes to your browser on save. To prevent a few common issues, see
https://code.thheller.com/blog/shadow-cljs/2019/08/25/hot-reload-in-clojurescript.html#things-to-avoid[Hot Reload in ClojureScript: Things to avoid].

Opening the app in your browser starts a
https://clojurescript.org/reference/repl#using-the-browser-as-an-evaluation-environment[ClojureScript browser REPL],
to which you may now connect.

==== Connecting to the browser REPL from Emacs with CIDER

Connect to the browser REPL:

----
M-x cider-jack-in-cljs
----

See
https://shadow-cljs.github.io/docs/UsersGuide.html#cider[Shadow CLJS User's Guide: Emacs/CIDER]
for more information. Note that the mentioned `.dir-locals.el` file has already
been created for you.

==== Connecting to the browser REPL from VS Code with Calva

See the https://github.com/day8/re-frame-template[re-frame-template README] for https://github.com/BetterThanTomorrow/calva[Calva] instuctions. See also https://calva.io for Calva documentation.

==== Connecting to the browser REPL from other editors

See
https://shadow-cljs.github.io/docs/UsersGuide.html#_editor_integration[Shadow CLJS User's Guide: Editor Integration].
Note that `npm run watch` runs `npx shadow-cljs watch` for you, and that this project's running build ids is
`app`, `browser-test`, `karma-test`, or the keywords `:app`, `:browser-test`, `:karma-test` in a Clojure context.

Alternatively, search the web for info on connecting to a `shadow-cljs` ClojureScript browser REPL
from your editor and configuration.

For example, in Vim / Neovim with `fireplace.vim`

. Open a `.cljs` file in the project to activate `fireplace.vim`
. In normal mode, execute the `Piggieback` command with this project's running build id, `:app`:
+
[source,vim]
----
 :Piggieback :app
----

==== Connecting to the browser REPL from a terminal

. Connect to the `shadow-cljs` nREPL:
+
[source,sh]
----
 lein repl :connect localhost:8777
----
+
The REPL prompt, `+shadow.user=>+`, indicates that is a Clojure REPL, not ClojureScript.

. In the REPL, switch the session to this project's running build id, `:app`:
+
[source,clj]
----
 (shadow.cljs.devtools.api/nrepl-select :app)
----
+
The REPL prompt changes to `+cljs.user=>+`, indicating that this is now a ClojureScript REPL.

. See `user.cljs` for symbols that are immediately accessible in the REPL
without needing to `require`.

=== Running `shadow-cljs` Actions

See a list of https://shadow-cljs.github.io/docs/UsersGuide.html#_command_line[`shadow-cljs CLI`]
actions:

[source,sh]
----
npx shadow-cljs --help
----

Please be patient; it may take over 10 seconds to see any output. Also note that some actions shown
may not actually be supported, outputting "Unknown action." when run.

Run a shadow-cljs action on this project's build id (without the colon, just `app`):

[source,sh]
----
npx shadow-cljs <action> app
----

=== Debug Logging

The `debug?` variable in `config.cljs` defaults to `true` in
<<running-the-app,`dev`>> builds, and `false` in <<production,`prod`>> builds.

Use `debug?` for logging or other tasks that should run only on `dev` builds:

[source,clj]
----
(ns web-app.example
  (:require [web-app.config :as config])

(when config/debug?
  (println "This message will appear in the browser console only on dev builds."))
----

== Production

Build the app with the `prod` profile:

[source,sh]
----
npm install
npm run release
----

Please be patient; it may take over 15 seconds to see any output, and over 30 seconds to complete.

The `resources/public/js/compiled` directory is created, containing the compiled `app.js` and
`manifest.edn` files.

